### ISSUE TITLE
[FILES] Missing front files

### ISSUE THREAD

**Issue by LedgendODST** [headassbtw/CustomMenuText#2]
**Custom Front File Missing**

can not find the custom front file, the Link you provided is the Project source, ( https://github.com/artemiswkearney/CustomMenuText/files/2972909/CustomMenuFont.zip ) 

**Expected behavior**
get the front files.

**Comment by headassbtw** [comment]
might be an issue with you, but when i click the link, it just starts downloading a zip file

**Comment by LedgendODST** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/55636493/118004885-2aaf1080-b34a-11eb-9c13-54b9d3537384.png)

this is what i get from the Download, this might be really unnecessary because it's a whole Project, so why put a whole Source Code into the UserData folder?

**Comment by headassbtw** [comment]
that's not how it works,
you open the project in unity, import a font, convert it with the TextMeshPro tools, then export the prefab as an AssetBundle

later on i will make a less confusing unity project for this, or maybe even a hands-off converter, but this is how it is for now
you'll sort of understand this process if you've done custom sabers before

also unity loves shoving a solution in there, ignore it

**Comment by LedgendODST** [comment]
oooohh then sorry, i thought you just wanted to Give people the Files just for the Skin. just liike this, i was really confused about it, i a sorrryyyyyyyyyyyyyyy

[image](https://user-images.githubusercontent.com/55636493/118041433-129fb700-b373-11eb-9b2d-50449f6f136c.png)

**Comment by headassbtw** [comment]
it's all good, i understand the confusion lol, i don't do the best job at making things clear

also for the record, beon, neon tubes 2, and teko are built in to the mod itself, you don't need to add them in after the fact
