### ISSUE TITLE
[BUG] Unity Project produces unuseable assetbundles

### ISSUE THREAD

**Issue by eeveeishpowered** [headassbtw/CustomMenuText#3]
**Describe the bug**
All of the font assetbundles I've tried to produce just end up with the CustomMenuText plugin not loading, or the game crashing on boot-up if the filesize is large.

**To Reproduce**
1. Open the Unity Project, import fonts that you want to build
2. Right click the font and create a Text Asset using the font
3. Click on the Text Asset, click on Update atlas texture, set character set to ASCII, then generate Font Atlass, then give it a label under AssetBundle, then right click the Text Asset and click Build AssetBundle
4. Copy over the generated AssetBundle to the Fonts folder in UserData, then open the game to see that the CustomMenuText plugin failed to load/game hangs with a white screen on startup.

**Expected behavior**
The font would load correctly and would be choosable in the CustomMenuText settings

**Screenshots**
![image](https://user-images.githubusercontent.com/82042525/118396922-9eeafc00-b649-11eb-91d8-df1462a1a208.png)
The place where I gave the Text Asset a label.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro version 2004
 - Browser: Google Chrome
 - Version: Plugin Version is v3.3.0, Unity Version is 2018.4.35f1

**Additional context**
My broken generated asset font has a weirdly small filesize compared to (for example) the Comic Sans font that the creator posted in #other-files in BSMG.
My file size: 77KB
Their file size: 2.17MB

**Comment by headassbtw** [comment]
not sure if this will help, but it's on me that i didn't elaborate the workflow that worked for me:

import ttf,
create font material with the TMPro window
*open the pre-exsting text prefab,*
*change the font within the prefab*
export the assetbundle using the menu in the assets tab



i plan to make a better version of the unity project, once i get around to it

**Comment by headassbtw** [comment]
I've updated the unity project to be massively simpler, and almost one-click, [Here's the download](https://github.com/headassbtw/CustomMenuText/raw/master/CustomMenuFont.zip)

the menu is at the top, under "CustomMenuText/Font Converter"
